### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by liangzi-chen** [NVIDIA/edk2-nvidia#23]
When I build edk2 - nvidia/Platform/nvidia/Jetson/build. Sh, there will be such a mistake.

Traceback (most recent call last):
  File "edk2/BaseTools/Edk2ToolsBuild.py", line 177, in <module>
    main()
  File "edk2/BaseTools/Edk2ToolsBuild.py", line 173, in main
    Edk2ToolsBuild().Invoke()
  File "/home/user/Jetson_UEFI/nvidia-uefi/venv/lib/python3.8/site-packages/edk2toolext/base_abstract_invocable.py", line 146, in Invoke
    retcode = self.Go()
  File "edk2/BaseTools/Edk2ToolsBuild.py", line 148, in Go
    raise Exception("Failed to build.")
Exception: Failed to build.

**Comment by jgarver** [comment]
@liangzi-chen Thank you for reporting this and sorry for the slow response.  Please try applying the patch in #24 and see if that resolves the issue.  Thanks!

**Comment by jgarver** [comment]
This fix has been added to the main branch.
