### ISSUE TITLE
AttributeError: 'Edk2Update' object has no attribute 'PlatformModule'

### ISSUE THREAD

**Issue by fadhelh-nd** [NVIDIA/edk2-nvidia#85]
Hi,
When following the docs to build UEFI without docker(https://github.com/NVIDIA/edk2-nvidia/wiki/Build-without-docker)
Encountered below error with 
[main]$ edk2-nvidia/Platform/NVIDIA/Jetson/build.sh

nvidia: building from workspace rooted at: /home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi
nvidia: found command: python3.
nvidia: found command: virtualenv.
nvidia: found command: mono.
nvidia: found command: aarch64-linux-gnu-gcc.
nvidia: found Python 3.9 or later.
nvidia: Activating Python virtual environment.
nvidia: Updating build environment (edk2-nvidia/Platform/NVIDIA/Jetson/PlatformBuild.py).
Unable to use edk2-nvidia/Platform/NVIDIA/Jetson/PlatformBuild.py as a UpdateSettingsManager
Did you mean to use a different kind of invocable?
Traceback (most recent call last):
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toolext/edk2_invocable.py", line 355, in ParseCommandLineOptions
    self.PlatformModule = import_module_by_file_name(os.path.abspath(settingsArg.platform_module))
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toollib/utility_functions.py", line 347, in import_module_by_file_name
    spec.loader.exec_module(ImportedModule)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi/edk2-nvidia/Platform/NVIDIA/Jetson/PlatformBuild.py", line 10, in <module>
    from edk2nv.stuart import NVIDIASettingsManager, NVIDIAPlatformBuilder
  File "/home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi/edk2-nvidia/Silicon/NVIDIA/edk2nv/stuart/__init__.py", line 10, in <module>
    from .builder import *  # noqa
  File "/home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi/edk2-nvidia/Silicon/NVIDIA/edk2nv/stuart/builder.py", line 12, in <module>
    from edk2toolext.environment.uefi_build import UefiBuilder
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toolext/environment/uefi_build.py", line 24, in <module>
    from edk2toollib.uefi.edk2.parsers.dsc_parser import DscParser
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toollib/uefi/edk2/parsers/dsc_parser.py", line 13, in <module>
    from edk2toollib.uefi.edk2.parsers.base_parser import HashFileParser
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toollib/uefi/edk2/parsers/base_parser.py", line 13, in <module>
    from edk2toollib.uefi.edk2 import path_utilities
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toollib/uefi/edk2/path_utilities.py", line 21, in <module>
    class Edk2Path(object):
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toollib/uefi/edk2/path_utilities.py", line 329, in Edk2Path
    def GetContainingModules(self, input_path: str) -> list[str]:
TypeError: 'type' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fadhelh/.local/bin/stuart_update", line 8, in <module>
    sys.exit(main())
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toolext/invocables/edk2_update.py", line 120, in main
    Edk2Update().Invoke()
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toolext/base_abstract_invocable.py", line 200, in Invoke
    self.ParseCommandLineOptions()
  File "/home/fadhelh/.local/lib/python3.8/site-packages/edk2toolext/edk2_invocable.py", line 367, in ParseCommandLineOptions
    Module = self.PlatformModule
AttributeError: 'Edk2Update' object has no attribute 'PlatformModule'

Please comment
Regards

**Comment by fadhelh-nd** [comment]
ubuntu version: 20.04.1
python3 version: 3.9.5

**Comment by jgarver** [comment]
@fadhelh-nd Sorry for the slow response.  Last week was a holiday week for much of our team.

Did you update source in place?  If so, perhaps you need to clobber your venv directory (rm -rf venv) and re-run build.sh.  It will create a new venv.

It appears to be seeing Python3.9, but is picking up python3.8 modules from /home/fadhelh/.local/lib.  I'm not sure how that's possible, but maybe it's because you have a stale venv.

**Comment by fadhelh-nd** [comment]
Hi @jgarver,
1. As mentioned i removed venv (rm -fr venv)
2.ls  /home/fadhelh/.local/lib
       python3.8 and python3.9
       Here i moved python3.8 outside for time being.
3. edk2-nvidia/Platform/NVIDIA/Jetson/build.sh
nvidia: building from workspace rooted at: /home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi
nvidia: found command: python3.
nvidia: found command: virtualenv.
nvidia: found command: mono.
nvidia: found command: aarch64-linux-gnu-gcc.
nvidia: found Python 3.9 or later.
nvidia: Creating Python virtual environment in /home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi/venv...
created virtual environment CPython3.8.10.final.0-64 in 107ms
  creator CPython3Posix(dest=/home/fadhelh/project/octo_v1/uefistrap/nvidia-uefi/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/fadhelh/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
nvidia: Installing required Python packages...
ERROR: Could not find a version that satisfies the requirement edk2-pytool-library==0.14.0 (from -r edk2/pip-requirements.txt (line 15)) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.12, 0.10.13, 0.10.15, 0.11.0, 0.11.1, 0.11.2, 0.11.4, 0.11.5, 0.11.6, 0.12.0, 0.12.1, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.18.0, 0.18.1, 0.18.2)
ERROR: No matching distribution found for edk2-pytool-library==0.14.0 (from -r edk2/pip-requirements.txt (line 15))


please comment

**Comment by jgarver** [comment]
It's still picking up Python 3.8.

This line indicates that "python3" in the path is pointing to Python3.9:
> nvidia: found Python 3.9 or later.

So, that's good.

But this line indicates virtualenv thinks python3 is Python3.8:
> created virtual environment CPython3.8.10.final.0-64 in 107ms

I'm not sure how virtualenv is picking up a different python3.

The virtualenv is created by edk2-nvidia/Silicon/NVIDIA/scripts/prepare_stuart.sh with this command:
$  virtualenv -p python3 venv

Things I'd check next:
* Do you have a PYTHONPATH set?
* Try editing edk2-nvidia/Silicon/NVIDIA/scripts/prepare_stuart.sh and change "virtualenv -p python3 venv" to "virtualenv -p python3.9 venv"
* Put virtualenv under a microscope and try to determine why it's not using the python3 in the path.

**Comment by jgarver** [comment]
I'd also recommend using the "Build with docker" approach.  It's much, much easier to get up and running.

**Comment by fadhelh-nd** [comment]
Hi @jgarver ,
After following instructions from below;
https://tellor.io/blog/how-to-install-python-3-9-and-venv-on-ubuntu/

i got things working again and build both jetson and server ..

hope below is the expected output

$ ll images/uefi_Jetson*.bin
-rw-rw-r-- 1 fadhelh fadhelh 2818048 Nov 28 18:01 images/uefi_Jetson_RELEASE.bin
-rw-rw-r-- 1 fadhelh fadhelh 3014656 Nov 28 18:14 images/uefi_Server_DEBUG.bin
-rw-rw-r-- 1 fadhelh fadhelh 2949120 Nov 28 18:18 images/uefi_Server_RELEASE.bin

**Comment by jgarver** [comment]
Looks good.
